#[macro_use]
extern crate lazy_static;


mod day_1;
mod day_2;
mod day_3;
mod day_4;
mod day_5;
mod day_6;
mod day_7;
mod day_8;
mod day_9;
mod day_10;
mod day_11;
mod day_12;
mod day_13;
mod day_14;
mod day_15;
mod day_16;
mod day_17;
mod day_18;
mod day_19;
mod day_20;
mod day_21;
mod day_22;
mod day_23;
mod day_24;
mod day_25;

fn main() {
    println!("Day 1: {}", day_1::run());
    println!("Day 1, pt2: {}", day_1::run_pt2());
    println!("Day 2: {}", day_2::run());
    println!("Day 2, pt2: {}", day_2::run_pt2());
    println!("Day 3: {}", day_3::run());
    println!("Day 3, pt2: {}", day_3::run_pt2());
    println!("Day 4, par: {}", day_4::run());
    println!("Day 4, par, pt2: {}", day_4::run_pt2());
    println!("Day 5: {}", day_5::run());
    println!("Day 5, pt2: {}", day_5::run_pt2());
    println!("Day 6: {}", day_6::run());
    println!("Day 6, pt2: {}", day_6::run_pt2());
    println!("Day 7: {}", day_7::run());
    println!("Day 7, pt2: {}", day_7::run_pt2());
    println!("Day 8: {}", day_8::run());
    println!("Day 8, pt2: {}", day_8::run_pt2());
    println!("Day 9: {}", day_9::run());
    println!("Day 9, pt2: {}", day_9::run_pt2());
    println!("Day 10: {}", day_10::run());
    println!("Day 10, pt2: {}", day_10::run_pt2());
    println!("Day 11: {}", day_11::run());
    println!("Day 11, pt2: {}", day_11::run_pt2());
    println!("Day 12: {}", day_12::run());
    println!("Day 12, pt2: {}", day_12::run_pt2());
    println!("Day 13: {}", day_13::run());
    println!("Day 13, pt2: {}", day_13::run_pt2());
    println!("Day 14: {}", day_14::run());
    println!("Day 14, pt2: {}", day_14::run_pt2());
    println!("Day 15: {}", day_15::run());
    println!("Day 15, pt2: {}", day_15::run_pt2());
    println!("Day 16: {}", day_16::run());
    println!("Day 16, pt2: {}", day_16::run_pt2());
    println!("Day 17: {}", day_17::run());
    println!("Day 17, pt2: {}", day_17::run_pt2());
    println!("Day 18: {}", day_18::run());
    println!("Day 18, pt2: {}", day_18::run_pt2());
    println!("Day 19: {}", day_19::run());
    println!("Day 19, pt2: {}", day_19::run_pt2());
    println!("Day 20: {}", day_20::run());
    println!("Day 20, pt2: {}", day_20::run_pt2());
    println!("Day 21: {}", day_21::run());
    println!("Day 21, pt2: {}", day_21::run_pt2());
    println!("Day 22: {}", day_22::run());
    println!("Day 22, pt2: {}", day_22::run_pt2());
    println!("Day 23: {}", day_23::run());
    println!("Day 23, pt2: {}", day_23::run_pt2());
    println!("Day 24: {}", day_24::run());
    println!("Day 24, pt2: {}", day_24::run_pt2());
    println!("Day 25: {}", day_25::run());
}
